name: tweet-release

on: 
  push:
    branches: '**'

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: Eomm/why-don-t-you-tweet@v1
        if: ${{ !github.event.repository.private }}
        with:
          tweet-message: " ${{ github.event.head_commit.message }}. \n
          ${{ github.event.repository.name }}. \n
          https://twitter.com/ImmutableOrg \n 
          #ImmutableOrganization #ethereum #Arbitrum
          "
        env:
          TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
